- id: numpydoc-validation
  name: numpydoc-validation
  description: This hook validates that docstrings in committed files adhere to numpydoc standards.
  entry: numpydoc lint
  require_serial: true
  language: python
  types: [python]
