version: 2
jobs:
    build_docs:
      docker:
        - image: circleci/python:3.7-stretch
      steps:
        - checkout
        - run:
            name: Set BASH_ENV
            command: |
              echo "set -e" >> $BASH_ENV;
              echo "export PATH=~/.local/bin:$PATH" >> $BASH_ENV;
              sudo apt update
              sudo apt install dvipng texlive-fonts-recommended texlive-latex-recommended texlive-latex-extra texlive-generic-extra latexmk texlive-xetex
        - restore_cache:
            keys:
              - pip-cache
        - run:
            name: Get dependencies and install
            command: |
              pip install --user -q --upgrade pip setuptools
              pip install --user -q --upgrade numpy matplotlib sphinx pydata-sphinx-theme
              pip install --user -e .
        - save_cache:
            key: pip-cache
            paths:
              - ~/.cache/pip
        - run:
            name: make html
            command: |
              make -C doc html
        - store_artifacts:
            path: doc/_build/html/
            destination: html
        - run:
            name: make tinybuild
            command: |
              make -C numpydoc/tests/tinybuild html
        - store_artifacts:
            path: numpydoc/tests/tinybuild/_build/html/
            destination: tinybuild

workflows:
  version: 2

  default:
    jobs:
      - build_docs
