name: style

on: [push, pull_request]

jobs:
  pre-commit:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - uses: pre-commit/action@v2.0.3
